;
; File generated by cc65 v 2.19 - Git 80ff9d3f4
;
	.fopt		compiler,"cc65 v 2.19 - Git 80ff9d3f4"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_kbhit
	.export		_main

.segment	"DATA"

_sprite_data:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$3C
	.byte	$00
	.byte	$00
	.byte	$FF
	.byte	$00
	.byte	$01
	.byte	$FF
	.byte	$80
	.byte	$03
	.byte	$FF
	.byte	$C0
	.byte	$07
	.byte	$FF
	.byte	$E0
	.byte	$0F
	.byte	$FF
	.byte	$F0
	.byte	$1F
	.byte	$FF
	.byte	$F8
	.byte	$1F
	.byte	$FF
	.byte	$F8
	.byte	$3F
	.byte	$FF
	.byte	$FC
	.byte	$3F
	.byte	$FF
	.byte	$FC
	.byte	$3F
	.byte	$FF
	.byte	$FC
	.byte	$1F
	.byte	$FF
	.byte	$F8
	.byte	$1F
	.byte	$FF
	.byte	$F8
	.byte	$0F
	.byte	$FF
	.byte	$F0
	.byte	$07
	.byte	$FF
	.byte	$E0
	.byte	$03
	.byte	$FF
	.byte	$C0
	.byte	$01
	.byte	$FF
	.byte	$80
	.byte	$00
	.byte	$FF
	.byte	$00
	.byte	$00
	.byte	$3C
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00

; ---------------------------------------------------------------
; void __near__ wait_vsync (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_wait_vsync: near

.segment	"CODE"

	jmp     L0002
L0002:	ldx     #$00
	lda     $D012
	cmp     #$FF
	jsr     booleq
	jne     L0002
	jmp     L0005
L0005:	ldx     #$00
	lda     $D012
	cmp     #$FF
	jsr     boolne
	jne     L0005
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp8
	ldx     #$00
	lda     #$28
	ldy     #$05
	jsr     staxysp
	ldx     #$00
	lda     #$50
	ldy     #$03
	jsr     staxysp
	ldx     #$00
	lda     #$01
	ldy     #$02
	sta     (c_sp),y
	ldx     #$00
	lda     #$01
	ldy     #$01
	sta     (c_sp),y
	ldx     #$00
	lda     #$00
	ldy     #$07
	sta     (c_sp),y
L0002:	ldy     #$07
	ldx     #$00
	lda     (c_sp),y
	cmp     #$3F
	jsr     boolult
	jne     L0005
	jmp     L0003
L0005:	ldx     #$20
	lda     #$00
	ldy     #$07
	clc
	adc     (c_sp),y
	bcc     L0006
	inx
L0006:	jsr     pushax
	lda     #<(_sprite_data)
	ldx     #>(_sprite_data)
	ldy     #$09
	clc
	adc     (c_sp),y
	bcc     L0007
	inx
L0007:	ldy     #$00
	jsr     ldauidx
	ldy     #$00
	jsr     staspidx
	ldy     #$07
	ldx     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
	jmp     L0002
L0003:	ldx     #$00
	lda     #$80
	sta     $07F8
	ldx     #$00
	lda     #$01
	sta     $D027
	ldx     #$00
	lda     #$01
	sta     $D015
	jmp     L000A
L0008:	jsr     _wait_vsync
	ldy     #$06
	jsr     ldaxysp
	cmp     #$19
	txa
	sbc     #$00
	bvc     L000C
	eor     #$80
L000C:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jne     L000D
	ldy     #$06
	jsr     ldaxysp
	cmp     #$40
	txa
	sbc     #$01
	bvs     L000E
	eor     #$80
L000E:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jne     L000D
	ldx     #$00
	lda     #$00
	jeq     L000F
L000D:	ldx     #$00
	lda     #$01
L000F:	jeq     L000B
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	bpl     L0010
	dex
L0010:	jsr     negax
	ldx     #$00
	cmp     #$80
	bcc     L0011
	dex
L0011:	ldy     #$02
	sta     (c_sp),y
L000B:	ldy     #$04
	jsr     ldaxysp
	cmp     #$33
	txa
	sbc     #$00
	bvc     L0013
	eor     #$80
L0013:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jne     L0014
	ldy     #$04
	jsr     ldaxysp
	cmp     #$E6
	txa
	sbc     #$00
	bvs     L0015
	eor     #$80
L0015:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jne     L0014
	ldx     #$00
	lda     #$00
	jeq     L0016
L0014:	ldx     #$00
	lda     #$01
L0016:	jeq     L0012
	ldy     #$01
	ldx     #$00
	lda     (c_sp),y
	bpl     L0017
	dex
L0017:	jsr     negax
	ldx     #$00
	cmp     #$80
	bcc     L0018
	dex
L0018:	ldy     #$01
	sta     (c_sp),y
L0012:	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	bpl     L0019
	dex
L0019:	ldy     #$05
	jsr     addeqysp
	ldy     #$01
	ldx     #$00
	lda     (c_sp),y
	bpl     L001A
	dex
L001A:	ldy     #$03
	jsr     addeqysp
	ldx     #$00
	lda     #$00
	ldy     #$00
	sta     (c_sp),y
	ldy     #$06
	jsr     ldaxysp
	cmp     #$00
	txa
	sbc     #$01
	bvs     L001C
	eor     #$80
L001C:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jeq     L001B
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	ora     #$01
	ldy     #$00
	sta     (c_sp),y
L001B:	ldy     #$05
	ldx     #$00
	lda     (c_sp),y
	sta     $D000
	ldy     #$03
	ldx     #$00
	lda     (c_sp),y
	sta     $D001
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	sta     $D010
L000A:	jsr     _kbhit
	jsr     bnega
	jne     L0008
	ldx     #$00
	lda     #$00
	sta     $D015
	rts

.endproc

