;
; File generated by cc65 v 2.19 - Git 80ff9d3f4
;
	.fopt		compiler,"cc65 v 2.19 - Git 80ff9d3f4"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_printf
	.import		_clrscr
	.import		_isprint
	.export		_main

.segment	"RODATA"

S0001:
	.byte	$25,$33,$44,$25,$43,$20,$09,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp2
	jsr     _clrscr
	ldx     #$00
	lda     #$41
	ldy     #$00
	jsr     staxysp
L0002:	ldy     #$01
	jsr     ldaxysp
	cmp     #$00
	txa
	sbc     #$01
	bvc     L0006
	eor     #$80
L0006:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jne     L0005
	jmp     L0003
L0005:	ldy     #$01
	jsr     ldaxysp
	jsr     _isprint
	stx     tmp1
	ora     tmp1
	jeq     L0004
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$06
	jsr     _printf
L0004:	ldy     #$00
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0002
L0003:	ldx     #$00
	lda     #$00
	jmp     L0001
L0001:	rts

.endproc

