;
; File generated by cc65 v 2.19 - Git 80ff9d3f4
;
	.fopt		compiler,"cc65 v 2.19 - Git 80ff9d3f4"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_printf
	.import		_rand
	.import		_srand
	.import		_time
	.import		_clrscr
	.export		_randomize
	.export		_roll
	.export		_main

.segment	"RODATA"

S0001:
	.byte	$25,$44,$20,$25,$44,$0D,$00

; ---------------------------------------------------------------
; void __near__ randomize (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_randomize: near

.segment	"CODE"

	ldx     #$00
	lda     #$00
	jsr     _time
	jsr     _srand
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ roll (int *d1, int *d2)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_roll: near

.segment	"CODE"

	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	jsr     _rand
	jsr     pushax
	ldx     #$00
	lda     #$06
	jsr     tosmodax
	jsr     incax1
	ldy     #$00
	jsr     staxspidx
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	jsr     _rand
	jsr     pushax
	ldx     #$00
	lda     #$06
	jsr     tosmodax
	jsr     incax1
	ldy     #$00
	jsr     staxspidx
	jsr     incsp4
	rts

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp6
	jsr     _randomize
	jsr     _clrscr
	ldx     #$00
	lda     #$00
	ldy     #$04
	jsr     staxysp
L0002:	ldy     #$05
	jsr     ldaxysp
	cmp     #$0A
	txa
	sbc     #$00
	bvc     L0006
	eor     #$80
L0006:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jne     L0005
	jmp     L0003
L0005:	lda     #$02
	jsr     leaa0sp
	jsr     pushax
	lda     #$02
	jsr     leaa0sp
	jsr     _roll
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$06
	jsr     _printf
	ldy     #$04
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0002
L0003:	ldx     #$00
	lda     #$00
	jmp     L0001
L0001:	rts

.endproc

